name: Python test

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10"]

    steps:
      - uses: actions/checkout@v3
      - name: Setup firefox
        uses: browser-actions/setup-firefox@v1
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          sudo apt-get install -y chromium-browser
          python -m pip install --upgrade pip
          pip install requests webdriver-manager selenium pytest
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      - name: Run python tests
        run: |
          pytest -rA
          
